// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeoGarden.Data.EF;

#nullable disable

namespace TeoGarden.Data.Migrations
{
    [DbContext(typeof(TeoGardenDbContext))]
    [Migration("20220705113023_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("372ea575-2536-4076-9bab-3e3138de495f"),
                            RoleId = new Guid("9e87b492-5343-4272-9a34-fa5de7cffb22")
                        },
                        new
                        {
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            RoleId = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31")
                        },
                        new
                        {
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            RoleId = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens", (string)null);
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Cart", b =>
                {
                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("VegetableId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            VegetableId = 18,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            Amount = 2
                        },
                        new
                        {
                            VegetableId = 31,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            Amount = 1
                        },
                        new
                        {
                            VegetableId = 24,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            Amount = 3
                        },
                        new
                        {
                            VegetableId = 40,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            Amount = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 7, 5, 18, 30, 23, 449, DateTimeKind.Local).AddTicks(9760));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 7, 5, 18, 30, 23, 449, DateTimeKind.Local).AddTicks(9855));

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1995),
                            Image = "1.jpg",
                            IsDeleted = false,
                            Name = "Rau",
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1995)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1996),
                            Image = "2.jpg",
                            IsDeleted = false,
                            Name = "Củ",
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1997)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1997),
                            Image = "3.jpg",
                            IsDeleted = false,
                            Name = "Quả",
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1998)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1998),
                            Image = "4.jpg",
                            IsDeleted = false,
                            Name = "Nấm",
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1999)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1999),
                            Image = "5.jpg",
                            IsDeleted = false,
                            Name = "Bông",
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(2000)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(2001),
                            Image = "6.jpg",
                            IsDeleted = false,
                            Name = "Hạt",
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(2001)
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FeedbackTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(218));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("Vote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VegetableId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Rau tươi ngon",
                            FeedbackTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3682),
                            IsDeleted = false,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            VegetableId = 18,
                            Vote = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Rau héo",
                            FeedbackTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3684),
                            IsDeleted = false,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            VegetableId = 31,
                            Vote = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Rau tươi quá",
                            FeedbackTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3685),
                            IsDeleted = false,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            VegetableId = 24,
                            Vote = 4
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Rau không tươi",
                            FeedbackTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3686),
                            IsDeleted = false,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            VegetableId = 40,
                            Vote = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3636),
                            OrderTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3635),
                            StatusId = 1,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4")
                        },
                        new
                        {
                            Id = 2,
                            DeliveryTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3638),
                            OrderTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3638),
                            StatusId = 2,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4")
                        },
                        new
                        {
                            Id = 3,
                            DeliveryTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3640),
                            OrderTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3640),
                            StatusId = 3,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15")
                        },
                        new
                        {
                            Id = 4,
                            DeliveryTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3641),
                            OrderTime = new DateTime(2022, 7, 5, 18, 30, 23, 454, DateTimeKind.Local).AddTicks(3641),
                            StatusId = 1,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15")
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.OrderDetail", b =>
                {
                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("OrderPrice")
                        .HasColumnType("int");

                    b.HasKey("VegetableId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            VegetableId = 1,
                            OrderId = 1,
                            Amount = 2,
                            OrderPrice = 5000
                        },
                        new
                        {
                            VegetableId = 10,
                            OrderId = 1,
                            Amount = 1,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 26,
                            OrderId = 1,
                            Amount = 2,
                            OrderPrice = 10000
                        },
                        new
                        {
                            VegetableId = 8,
                            OrderId = 2,
                            Amount = 3,
                            OrderPrice = 10000
                        },
                        new
                        {
                            VegetableId = 40,
                            OrderId = 2,
                            Amount = 2,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 33,
                            OrderId = 3,
                            Amount = 2,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 28,
                            OrderId = 4,
                            Amount = 2,
                            OrderPrice = 5000
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chưa xử lý"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Đang chuẩn bị"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Đang giao hàng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đã giao hàng"
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default.png");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegisteredDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 7, 5, 18, 30, 23, 449, DateTimeKind.Local).AddTicks(8257));

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 7, 5, 18, 30, 23, 449, DateTimeKind.Local).AddTicks(8401));

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            AccessFailedCount = 0,
                            Address = "Cộng Hòa, Q.Tân Bình, TP.HCM",
                            Avatar = "lam.jpg",
                            ConcurrencyStamp = "6cfd6c99-d6bf-48de-b0c2-8899f065a7a6",
                            Email = "lam@gmail.com",
                            EmailConfirmed = false,
                            IsBlocked = false,
                            LockoutEnabled = false,
                            Name = "Nguyễn Tùng Lâm",
                            Password = "AQAAAAEAACcQAAAAEHv6QY3RJ6yplVbF3fm4p1H5aARz/+mF19SxkdURBH0lGe1NRtyL4DxOgbt8DtpiNg==",
                            Phone = "0338307449",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            AccessFailedCount = 0,
                            Address = "Phan Đăng Lưu, Q.Phú Nhuận, TP.HCM",
                            Avatar = "an.jpg",
                            ConcurrencyStamp = "6411482c-1cb6-4968-b353-b033eb4641e6",
                            Email = "an@gmail.com",
                            EmailConfirmed = false,
                            IsBlocked = false,
                            LockoutEnabled = false,
                            Name = "Nguyễn Văn An",
                            Password = "AQAAAAEAACcQAAAAEK2/HyIhBCHpfQDpw75fijRSQNRQt4gt7OuYZIGnBi22zQstLNSRk+zOLN3saa2FaQ==",
                            Phone = "0338307449",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = new Guid("372ea575-2536-4076-9bab-3e3138de495f"),
                            AccessFailedCount = 0,
                            Address = "Califonia, Hoa Kỳ",
                            Avatar = "admin.jpg",
                            ConcurrencyStamp = "df1a72ac-4712-43b9-9131-04b3bae11c04",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            IsBlocked = false,
                            LockoutEnabled = false,
                            Name = "John",
                            Password = "AQAAAAEAACcQAAAAEEmem5soddUz91CScRlN/Q/JQ0+Sk2eb+bEtrnmqkQZsAVDUCEAj3XWZjtSNGuJc/g==",
                            Phone = "0338307449",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e87b492-5343-4272-9a34-fa5de7cffb22"),
                            ConcurrencyStamp = "9b254e80-48e7-4476-965b-fd897a6c5915",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31"),
                            ConcurrencyStamp = "f1595b50-cf9c-4c24-b52d-e7638bca125e",
                            Description = "Customer role",
                            Name = "customer",
                            NormalizedName = "customer"
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Vegetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 7, 5, 18, 30, 23, 449, DateTimeKind.Local).AddTicks(9145));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<double>("Stars")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime?>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 7, 5, 18, 30, 23, 449, DateTimeKind.Local).AddTicks(9263));

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Vegetables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1842),
                            Image = "1.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bạc hà",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1844),
                            Weight = 500
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1846),
                            Image = "2.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp cải tím",
                            Price = 15000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1846),
                            Weight = 500
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1848),
                            Image = "3.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp cải trắng",
                            Price = 15000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1848),
                            Weight = 500
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1849),
                            Image = "4.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp chuối bào",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1849),
                            Weight = 500
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1850),
                            Image = "5.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp non",
                            Price = 25000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1851),
                            Weight = 500
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1852),
                            Image = "6.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bầu",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1852),
                            Weight = 500
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1853),
                            Image = "8.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí đao",
                            Price = 8000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1853),
                            Weight = 500
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1854),
                            Image = "8.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí đỏ",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1855),
                            Weight = 500
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1856),
                            Image = "9.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí ngòi",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1857),
                            Weight = 500
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1858),
                            Image = "10.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông bí",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1858),
                            Weight = 500
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1859),
                            Image = "11.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông hẹ",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1860),
                            Weight = 500
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1861),
                            Image = "12.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông so đũa",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1861),
                            Weight = 500
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1862),
                            Image = "13.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông thiên lý",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1862),
                            Weight = 500
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1863),
                            Image = "14.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà chua",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1864),
                            Weight = 500
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1865),
                            Image = "15.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà pháo",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1865),
                            Weight = 500
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1866),
                            Image = "6.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà rốt",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1866),
                            Weight = 500
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1867),
                            Image = "17.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà tím",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1869),
                            Weight = 500
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1870),
                            Image = "18.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ dưa",
                            Price = 5000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1870),
                            Weight = 500
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1871),
                            Image = "19.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ dún",
                            Price = 5000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1871),
                            Weight = 500
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1872),
                            Image = "20.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ xanh",
                            Price = 5000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1873),
                            Weight = 500
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1874),
                            Image = "21.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bó xôi",
                            Price = 15000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1874),
                            Weight = 500
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1875),
                            Image = "22.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải ngọt",
                            Price = 5000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1875),
                            Weight = 500
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1876),
                            Image = "23.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải thảo",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1877),
                            Weight = 500
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1878),
                            Image = "24.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải xà lách",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1878),
                            Weight = 500
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1879),
                            Image = "25.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách tím",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1879),
                            Weight = 500
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1880),
                            Image = "26.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách xoang",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1881),
                            Weight = 500
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1881),
                            Image = "27.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách lụa",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1882),
                            Weight = 500
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1883),
                            Image = "28.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần dày lá",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1883),
                            Weight = 500
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1885),
                            Image = "29.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần tây",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1885),
                            Weight = 500
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1886),
                            Image = "30.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần ô",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1887),
                            Weight = 500
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1888),
                            Image = "31.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Chanh",
                            Price = 20000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1888),
                            Weight = 500
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1889),
                            Image = "32.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Củ cải trắng",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1889),
                            Weight = 500
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1890),
                            Image = "33.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Củ dền",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1891),
                            Weight = 500
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1891),
                            Image = "34.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu bắp",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1892),
                            Weight = 500
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1893),
                            Image = "35.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu đũa",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1893),
                            Weight = 500
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1894),
                            Image = "36.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu Hà Lan",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1895),
                            Weight = 500
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1896),
                            Image = "37.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu que",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1896),
                            Weight = 500
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1897),
                            Image = "38.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu rồng",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1897),
                            Weight = 500
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1898),
                            Image = "39.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu ván",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1899),
                            Weight = 500
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1899),
                            Image = "40.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Dưa gan",
                            Price = 10000,
                            Stars = 0.0,
                            UpdatedDate = new DateTime(2022, 7, 5, 18, 30, 23, 450, DateTimeKind.Local).AddTicks(1900),
                            Weight = 500
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Cart", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Feedback", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Order", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.OrderDetail", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Vegetable", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Category", "Category")
                        .WithMany("Vegetables")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Category", b =>
                {
                    b.Navigation("Vegetables");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
