// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeoGarden.Data.EF;

#nullable disable

namespace TeoGarden.Data.Migrations
{
    [DbContext(typeof(TeoGardenDbContext))]
    [Migration("20220627100745_version6")]
    partial class version6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TeoGarden.Data.Models.Cart", b =>
                {
                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("VegetableId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            VegetableId = 18,
                            UserId = 1,
                            Amount = 2
                        },
                        new
                        {
                            VegetableId = 31,
                            UserId = 1,
                            Amount = 1
                        },
                        new
                        {
                            VegetableId = 24,
                            UserId = 1,
                            Amount = 3
                        },
                        new
                        {
                            VegetableId = 40,
                            UserId = 2,
                            Amount = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9253),
                            Image = "1.jpg",
                            IsDeleted = false,
                            Name = "Rau",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9254)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9257),
                            Image = "2.jpg",
                            IsDeleted = false,
                            Name = "Củ",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9258)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9260),
                            Image = "3.jpg",
                            IsDeleted = false,
                            Name = "Quả",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9261)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9263),
                            Image = "4.jpg",
                            IsDeleted = false,
                            Name = "Nấm",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9264)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9308),
                            Image = "5.jpg",
                            IsDeleted = false,
                            Name = "Bông",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9309)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9311),
                            Image = "6.jpg",
                            IsDeleted = false,
                            Name = "Hạt",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9312)
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FeedbackTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("Vote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VegetableId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Rau tươi ngon",
                            FeedbackTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9502),
                            IsDeleted = false,
                            UserId = 1,
                            VegetableId = 18,
                            Vote = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Rau héo",
                            FeedbackTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9504),
                            IsDeleted = false,
                            UserId = 1,
                            VegetableId = 31,
                            Vote = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Rau tươi quá",
                            FeedbackTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9506),
                            IsDeleted = false,
                            UserId = 2,
                            VegetableId = 24,
                            Vote = 4
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Rau không tươi",
                            FeedbackTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9508),
                            IsDeleted = false,
                            UserId = 2,
                            VegetableId = 40,
                            Vote = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9414),
                            OrderTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9413),
                            StatusId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeliveryTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9418),
                            OrderTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9416),
                            StatusId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DeliveryTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9421),
                            OrderTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9420),
                            StatusId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            DeliveryTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9423),
                            OrderTime = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9422),
                            StatusId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.OrderDetail", b =>
                {
                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("OrderPrice")
                        .HasColumnType("int");

                    b.HasKey("VegetableId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            VegetableId = 1,
                            OrderId = 1,
                            Amount = 2,
                            OrderPrice = 5000
                        },
                        new
                        {
                            VegetableId = 10,
                            OrderId = 1,
                            Amount = 1,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 26,
                            OrderId = 1,
                            Amount = 2,
                            OrderPrice = 10000
                        },
                        new
                        {
                            VegetableId = 8,
                            OrderId = 2,
                            Amount = 3,
                            OrderPrice = 10000
                        },
                        new
                        {
                            VegetableId = 40,
                            OrderId = 2,
                            Amount = 2,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 33,
                            OrderId = 3,
                            Amount = 2,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 28,
                            OrderId = 4,
                            Amount = 2,
                            OrderPrice = 5000
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chưa xử lý"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Đang chuẩn bị"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Đang giao hàng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đã giao hàng"
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default.png");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cộng Hòa, Q.Tân Bình, TP.HCM",
                            Avatar = "lam.jpg",
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9345),
                            Email = "lam@gmail.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            Name = "Nguyễn Tùng Lâm",
                            Password = "12345",
                            Phone = "0338307449",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9346)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Phan Đăng Lưu, Q.Phú Nhuận, TP.HCM",
                            Avatar = "an.jpg",
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9350),
                            Email = "an@gmail.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            Name = "Nguyễn Văn An",
                            Password = "12345",
                            Phone = "0338307449",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9351)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Califonia, Hoa Kỳ",
                            Avatar = "admin.jpg",
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9353),
                            Email = "admin@gmail.com",
                            IsAdmin = true,
                            IsBlocked = false,
                            Name = "John",
                            Password = "12345",
                            Phone = "0338307449",
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9354)
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Vegetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Vegetables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8919),
                            Image = "1.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bạc hà",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8936),
                            Weight = 500
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8938),
                            Image = "2.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp cải tím",
                            Price = 15000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8939),
                            Weight = 500
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8941),
                            Image = "3.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp cải trắng",
                            Price = 15000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8942),
                            Weight = 500
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8943),
                            Image = "4.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp chuối bào",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8944),
                            Weight = 500
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8947),
                            Image = "5.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp non",
                            Price = 25000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8948),
                            Weight = 500
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8949),
                            Image = "6.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bầu",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8950),
                            Weight = 500
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8952),
                            Image = "8.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí đao",
                            Price = 8000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8953),
                            Weight = 500
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8954),
                            Image = "8.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí đỏ",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8955),
                            Weight = 500
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8957),
                            Image = "9.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí ngòi",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8958),
                            Weight = 500
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8959),
                            Image = "10.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông bí",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8960),
                            Weight = 500
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8962),
                            Image = "11.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông hẹ",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8962),
                            Weight = 500
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8964),
                            Image = "12.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông so đũa",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8965),
                            Weight = 500
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8967),
                            Image = "13.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông thiên lý",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8967),
                            Weight = 500
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8969),
                            Image = "14.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà chua",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8970),
                            Weight = 500
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8973),
                            Image = "15.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà pháo",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8973),
                            Weight = 500
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8975),
                            Image = "6.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà rốt",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8976),
                            Weight = 500
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8978),
                            Image = "17.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà tím",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8978),
                            Weight = 500
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8980),
                            Image = "18.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ dưa",
                            Price = 5000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8981),
                            Weight = 500
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8983),
                            Image = "19.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ dún",
                            Price = 5000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8983),
                            Weight = 500
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8985),
                            Image = "20.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ xanh",
                            Price = 5000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8986),
                            Weight = 500
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8988),
                            Image = "21.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bó xôi",
                            Price = 15000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8988),
                            Weight = 500
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8990),
                            Image = "22.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải ngọt",
                            Price = 5000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8991),
                            Weight = 500
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8993),
                            Image = "23.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải thảo",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8993),
                            Weight = 500
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8995),
                            Image = "24.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải xà lách",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8996),
                            Weight = 500
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(8999),
                            Image = "25.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách tím",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9000),
                            Weight = 500
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9001),
                            Image = "26.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách xoang",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9002),
                            Weight = 500
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9004),
                            Image = "27.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách lụa",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9004),
                            Weight = 500
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9006),
                            Image = "28.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần dày lá",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9007),
                            Weight = 500
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9009),
                            Image = "29.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần tây",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9010),
                            Weight = 500
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9011),
                            Image = "30.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần ô",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9012),
                            Weight = 500
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9053),
                            Image = "31.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Chanh",
                            Price = 20000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9054),
                            Weight = 500
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9056),
                            Image = "32.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Củ cải trắng",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9057),
                            Weight = 500
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9058),
                            Image = "33.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Củ dền",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9059),
                            Weight = 500
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9061),
                            Image = "34.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu bắp",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9062),
                            Weight = 500
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9063),
                            Image = "35.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu đũa",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9064),
                            Weight = 500
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9066),
                            Image = "36.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu Hà Lan",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9066),
                            Weight = 500
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9068),
                            Image = "37.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu que",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9069),
                            Weight = 500
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9070),
                            Image = "38.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu rồng",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9071),
                            Weight = 500
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9073),
                            Image = "39.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu ván",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9073),
                            Weight = 500
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9075),
                            Image = "40.jpg",
                            IsDeleted = false,
                            IsSale = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Dưa gan",
                            Price = 10000,
                            UpdatedDate = new DateTime(2022, 6, 27, 17, 7, 44, 294, DateTimeKind.Local).AddTicks(9076),
                            Weight = 500
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Cart", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Feedback", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Order", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.OrderDetail", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Vegetable", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Category", "Category")
                        .WithMany("Vegetables")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Category", b =>
                {
                    b.Navigation("Vegetables");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
