// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeoGarden.Data.EF;

#nullable disable

namespace TeoGarden.Data.Migrations
{
    [DbContext(typeof(TeoGardenDbContext))]
    [Migration("20220627093842_version3")]
    partial class version3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TeoGarden.Data.Models.Cart", b =>
                {
                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("VegetableId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            VegetableId = 18,
                            UserId = 1,
                            Amount = 2
                        },
                        new
                        {
                            VegetableId = 31,
                            UserId = 1,
                            Amount = 1
                        },
                        new
                        {
                            VegetableId = 24,
                            UserId = 1,
                            Amount = 3
                        },
                        new
                        {
                            VegetableId = 40,
                            UserId = 2,
                            Amount = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3573),
                            Image = "1.jpg",
                            IsDeleted = false,
                            Name = "Rau",
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3575)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3646),
                            Image = "2.jpg",
                            IsDeleted = false,
                            Name = "Củ",
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3647)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3649),
                            Image = "3.jpg",
                            IsDeleted = false,
                            Name = "Quả",
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3650)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3651),
                            Image = "4.jpg",
                            IsDeleted = false,
                            Name = "Nấm",
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3652)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3654),
                            Image = "5.jpg",
                            IsDeleted = false,
                            Name = "Bông",
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3654)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3656),
                            Image = "6.jpg",
                            IsDeleted = false,
                            Name = "Hạt",
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3657)
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FeedbackTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("Vote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VegetableId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Rau tươi ngon",
                            FeedbackTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3803),
                            IsDeleted = false,
                            UserId = 1,
                            VegetableId = 18,
                            Vote = 5
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Rau héo",
                            FeedbackTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3806),
                            IsDeleted = false,
                            UserId = 1,
                            VegetableId = 31,
                            Vote = 3
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Rau tươi quá",
                            FeedbackTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3808),
                            IsDeleted = false,
                            UserId = 2,
                            VegetableId = 24,
                            Vote = 4
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Rau không tươi",
                            FeedbackTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3810),
                            IsDeleted = false,
                            UserId = 2,
                            VegetableId = 40,
                            Vote = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3736),
                            OrderTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3734),
                            StatusId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeliveryTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3739),
                            OrderTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3738),
                            StatusId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DeliveryTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3741),
                            OrderTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3740),
                            StatusId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            DeliveryTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3743),
                            OrderTime = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3742),
                            StatusId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.OrderDetail", b =>
                {
                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("OrderPrice")
                        .HasColumnType("int");

                    b.HasKey("VegetableId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            VegetableId = 1,
                            OrderId = 1,
                            Amount = 2,
                            OrderPrice = 5000
                        },
                        new
                        {
                            VegetableId = 10,
                            OrderId = 1,
                            Amount = 1,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 26,
                            OrderId = 1,
                            Amount = 2,
                            OrderPrice = 10000
                        },
                        new
                        {
                            VegetableId = 8,
                            OrderId = 2,
                            Amount = 3,
                            OrderPrice = 10000
                        },
                        new
                        {
                            VegetableId = 40,
                            OrderId = 2,
                            Amount = 2,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 33,
                            OrderId = 3,
                            Amount = 2,
                            OrderPrice = 15000
                        },
                        new
                        {
                            VegetableId = 28,
                            OrderId = 4,
                            Amount = 2,
                            OrderPrice = 5000
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chưa xử lý"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Đang chuẩn bị"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Đang giao hàng"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Đã giao hàng"
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default.png");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cộng Hòa, Q.Tân Bình, TP.HCM",
                            Avatar = "lam.jpg",
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3681),
                            Email = "lam@gmail.com",
                            IsBlocked = false,
                            Name = "Nguyễn Tùng Lâm",
                            Password = "12345",
                            Phone = "0338307449",
                            Role = 0,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3682)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Phan Đăng Lưu, Q.Phú Nhuận, TP.HCM",
                            Avatar = "an.jpg",
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3685),
                            Email = "an@gmail.com",
                            IsBlocked = false,
                            Name = "Nguyễn Văn An",
                            Password = "12345",
                            Phone = "0338307449",
                            Role = 0,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3686)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Califonia, Hoa Kỳ",
                            Avatar = "admin.jpg",
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3688),
                            Email = "admin@gmail.com",
                            IsBlocked = false,
                            Name = "Jonson Admin",
                            Password = "12345",
                            Phone = "0338307449",
                            Role = 1,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3689)
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Vegetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("Sale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Vegetables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3294),
                            Image = "1.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bạc hà",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3309),
                            Weight = 500
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3311),
                            Image = "2.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp cải tím",
                            Price = 15000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3312),
                            Weight = 500
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3314),
                            Image = "3.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp cải trắng",
                            Price = 15000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3315),
                            Weight = 500
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3317),
                            Image = "4.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp chuối bào",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3318),
                            Weight = 500
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3320),
                            Image = "5.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bắp non",
                            Price = 25000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3321),
                            Weight = 500
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3323),
                            Image = "6.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bầu",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3324),
                            Weight = 500
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3326),
                            Image = "8.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí đao",
                            Price = 8000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3327),
                            Weight = 500
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3329),
                            Image = "8.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí đỏ",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3329),
                            Weight = 500
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3331),
                            Image = "9.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bí ngòi",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3332),
                            Weight = 500
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3334),
                            Image = "10.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông bí",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3334),
                            Weight = 500
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3336),
                            Image = "11.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông hẹ",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3337),
                            Weight = 500
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3339),
                            Image = "12.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông so đũa",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3340),
                            Weight = 500
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3341),
                            Image = "13.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Bông thiên lý",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3342),
                            Weight = 500
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3344),
                            Image = "14.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà chua",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3345),
                            Weight = 500
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3346),
                            Image = "15.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà pháo",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3347),
                            Weight = 500
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3349),
                            Image = "6.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà rốt",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3350),
                            Weight = 500
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3352),
                            Image = "17.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cà tím",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3353),
                            Weight = 500
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3354),
                            Image = "18.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ dưa",
                            Price = 5000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3355),
                            Weight = 500
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3357),
                            Image = "19.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ dún",
                            Price = 5000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3358),
                            Weight = 500
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3359),
                            Image = "20.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bẹ xanh",
                            Price = 5000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3360),
                            Weight = 500
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3362),
                            Image = "21.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải bó xôi",
                            Price = 15000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3363),
                            Weight = 500
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3365),
                            Image = "22.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải ngọt",
                            Price = 5000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3366),
                            Weight = 500
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3367),
                            Image = "23.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải thảo",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3368),
                            Weight = 500
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3370),
                            Image = "24.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cải xà lách",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3371),
                            Weight = 500
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3373),
                            Image = "25.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách tím",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3373),
                            Weight = 500
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3375),
                            Image = "26.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách xoang",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3376),
                            Weight = 500
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3378),
                            Image = "27.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Xà lách lụa",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3380),
                            Weight = 500
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3381),
                            Image = "28.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần dày lá",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3382),
                            Weight = 500
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3384),
                            Image = "29.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần tây",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3385),
                            Weight = 500
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3387),
                            Image = "30.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Cần ô",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3388),
                            Weight = 500
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3389),
                            Image = "31.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Chanh",
                            Price = 20000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3390),
                            Weight = 500
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3392),
                            Image = "32.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Củ cải trắng",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3393),
                            Weight = 500
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3395),
                            Image = "33.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Củ dền",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3395),
                            Weight = 500
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3397),
                            Image = "34.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu bắp",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3398),
                            Weight = 500
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3400),
                            Image = "35.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu đũa",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3401),
                            Weight = 500
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3403),
                            Image = "36.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu Hà Lan",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3404),
                            Weight = 500
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3405),
                            Image = "37.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu que",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3406),
                            Weight = 500
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3408),
                            Image = "38.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu rồng",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3409),
                            Weight = 500
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3411),
                            Image = "39.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Đậu ván",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3411),
                            Weight = 500
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3413),
                            Image = "40.jpg",
                            IsDeleted = false,
                            Location = "Tổng công ty rau quả nông sản, cánh đồng nông sản sạch, xã Hòa Bình, huyện Trà Ôn, tỉnh Vĩnh Long",
                            Name = "Dưa gan",
                            Price = 10000,
                            Sale = false,
                            UpdatedDate = new DateTime(2022, 6, 27, 16, 38, 41, 94, DateTimeKind.Local).AddTicks(3414),
                            Weight = 500
                        });
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Cart", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Feedback", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Order", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.OrderDetail", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeoGarden.Data.Models.Vegetable", "Vegetable")
                        .WithMany()
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Vegetable", b =>
                {
                    b.HasOne("TeoGarden.Data.Models.Category", "Category")
                        .WithMany("Vegetables")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Category", b =>
                {
                    b.Navigation("Vegetables");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.Status", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TeoGarden.Data.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
